export interface Question {
  id: number;
  question: string;
  options: string[];
  correct: number;
  explanation: string;
}

export interface Theme {
  id: string;
  name: string;
  description: string;
  icon: string;
  color: string;
  totalQuestions: number;
}

export const themes: Theme[] = [
  {
    id: "coracao",
    name: "Coração",
    description: "Grandes Vasos",
    icon: "❤️",
    color: "from-rose-500 to-rose-600",
    totalQuestions: 40,
  },
  {
    id: "vascularizacao",
    name: "Vascularização",
    description: "Viscerocrânio e Pescoço",
    icon: "🫀",
    color: "from-red-500 to-red-600",
    totalQuestions: 30,
  },
  {
    id: "cavidade-oral",
    name: "Cavidade Oral",
    description: "Anatomia Bucal",
    icon: "👄",
    color: "from-pink-500 to-pink-600",
    totalQuestions: 30,
  },
  {
    id: "orelha",
    name: "Orelha",
    description: "Anatomia da Audição",
    icon: "👂",
    color: "from-purple-500 to-purple-600",
    totalQuestions: 20,
  },
  {
    id: "olho",
    name: "Olho",
    description: "Anatomia da Visão",
    icon: "👁️",
    color: "from-blue-500 to-blue-600",
    totalQuestions: 20,
  },
];

export const questions: Record<string, Question[]> = {
  coracao: [
    {
      id: 1,
      question: "Um paciente de 22 anos apresenta um quadro de AVC isquêmico. O ecocardiograma revela um Forame Oval Patente (FOP). Anatomicalmente, essa condição representa uma falha no fechamento da comunicação entre:",
      options: [
        "O ventrículo direito e o ventrículo esquerdo.",
        "O átrio direito e o átrio esquerdo.",
        "A aorta e o tronco pulmonar.",
        "A veia cava superior e o átrio direito.",
      ],
      correct: 1,
      explanation: "O FOP é uma falha no fechamento do forame oval, que comunica os átrios no feto.",
    },
    {
      id: 2,
      question: "Durante um exame físico, o médico localiza o ictus cordis no 5º espaço intercostal esquerdo, na linha hemiclavicular. Essa estrutura corresponde ao:",
      options: [
        "Ápice do coração, formado pelo ventrículo esquerdo.",
        "Ápice do coração, formado pelo átrio esquerdo.",
        "Base do coração, formada pelo ventrículo direito.",
        "Margem inferior do coração, formada pelo átrio direito.",
      ],
      correct: 0,
      explanation: "O ápice é o ponto inferolateral do VE, no 5º EIC.",
    },
    {
      id: 3,
      question: "Um paciente com insuficiência da valva mitral apresenta um sopro característico. De acordo com a anatomia e os princípios da circulação, o principal defeito dessa condição é o refluxo de sangue do:",
      options: [
        "Ventrículo direito para o átrio direito.",
        "Átrio esquerdo para o ventrículo esquerdo.",
        "Ventrículo esquerdo para o átrio esquerdo.",
        "Ventrículo esquerdo para a aorta.",
      ],
      correct: 2,
      explanation: "A valva mitral (bicúspide) separa AE de VE; sua insuficiência causa refluxo para o AE.",
    },
    {
      id: 4,
      question: "Um infarto agudo do miocárdio causado pela obstrução da artéria interventricular anterior (descendente anterior) provoca a morte de células musculares em qual região?",
      options: [
        "Átrio direito e nó sinoatrial.",
        "Septo interventricular anterior e ventrículo esquerdo.",
        "Face diafragmática do ventrículo direito.",
        "Base do coração e átrio esquerdo.",
      ],
      correct: 1,
      explanation: "A artéria descendente anterior supre a face anterior e o septo interventricular.",
    },
    {
      id: 5,
      question: "O seio coronário é a principal veia de drenagem do coração. Anatomicalmente, ele recebe a confluência das veias cardíacas magna e parva e se abre diretamente no:",
      options: [
        "Átrio esquerdo.",
        "Ventrículo direito através do cone arterial.",
        "Átrio direito através do óstio do seio coronário.",
        "Veia cava inferior.",
      ],
      correct: 2,
      explanation: "Toda a drenagem venosa do miocárdio converge para o seio coronário, que se abre no AD.",
    },
    {
      id: 6,
      question: "Sobre o pericárdio, a camada que está diretamente aderida ao miocárdio, também chamada de epicárdio, é a:",
      options: [
        "Lâmina parietal do pericárdio seroso.",
        "Lâmina visceral do pericárdio seroso.",
        "Camada externa do pericárdio fibroso.",
        "Endocárdio.",
      ],
      correct: 1,
      explanation: "O epicárdio é a lâmina visceral do pericárdio seroso.",
    },
    {
      id: 7,
      question: "No átrio direito, a estrutura que separa a parede anterior rugosa (músculos pectíneos) da parede posterior lisa (seio das veias cavas) é a:",
      options: [
        "Fossa oval.",
        "Crista terminal.",
        "Trabécula septomarginal.",
        "Válvula de Eustáquio.",
      ],
      correct: 1,
      explanation: "A crista terminal é a linha de separação entre as partes lisa e rugosa do AD.",
    },
    {
      id: 8,
      question: "Um cirurgião manipula o coração e identifica um feixe muscular curvo que atravessa a cavidade do ventrículo direito, indo do septo interventricular até a base do músculo papilar anterior. Trata-se da:",
      options: [
        "Crista supraventricular.",
        "Trabécula septomarginal (banda moderadora).",
        "Corda tendínea.",
        "Valva tricúspide.",
      ],
      correct: 1,
      explanation: "A banda moderadora é exclusiva do VD e conduz o ramo direito do fascículo AV.",
    },
    {
      id: 9,
      question: "Assinale a alternativa CORRETA sobre a pequena circulação (pulmonar):",
      options: [
        "Inicia no ventrículo esquerdo e termina no átrio direito.",
        "O sangue sai do ventrículo direito pelo tronco pulmonar em direção aos pulmões.",
        "As artérias pulmonares carregam sangue rico em oxigênio.",
        "O sangue retorna ao átrio direito pelas veias pulmonares.",
      ],
      correct: 1,
      explanation: "A pequena circulação leva sangue venoso do VD aos pulmões para hematose.",
    },
    {
      id: 10,
      question: "O esqueleto fibroso do coração possui diversas funções. Assinale a alternativa que indica uma função que NÃO pertence a essa estrutura:",
      options: [
        "Fornecer fixação para as válvulas das valvas.",
        "Atuar como isolante elétrico entre átrios e ventrículos.",
        "Impedir a distensão excessiva dos óstios das valvas.",
        "Iniciar o impulso elétrico como marca-passo natural.",
      ],
      correct: 3,
      explanation: "O esqueleto fibroso é colágeno denso; o marca-passo é o tecido nodal (nó SA).",
    },
    {
      id: 11,
      question: "As artérias coronárias são os primeiros ramos da aorta. O óstio da artéria coronária direita localiza-se no:",
      options: [
        "Seio da aorta direito (acima da valva aórtica).",
        "Arco aórtico, entre o tronco braquiocefálico e a carótida comum.",
        "Ventrículo esquerdo, logo abaixo da valva mitral.",
        "Tronco pulmonar.",
      ],
      correct: 0,
      explanation: "As coronárias nascem nos seios da aorta, logo acima das válvulas semilunares.",
    },
    {
      id: 12,
      question: "Um ferimento por arma branca no 4º espaço intercostal esquerdo, imediatamente lateral ao esterno, tem maior probabilidade de atingir a face esternocostal do coração, formada principalmente pelo:",
      options: [
        "Ventrículo esquerdo.",
        "Átrio esquerdo.",
        "Ventrículo direito.",
        "Átrio direito.",
      ],
      correct: 2,
      explanation: "A face esternocostal é formada principalmente pelo ventrículo direito.",
    },
    {
      id: 13,
      question: "O nó sinoatrial (SA), responsável por iniciar os batimentos cardíacos, localiza-se na:",
      options: [
        "Região posteroinferior do septo interatrial.",
        "Junção da veia cava superior com o átrio direito.",
        "Trabécula septomarginal do ventrículo direito.",
        "Base do ventrículo esquerdo.",
      ],
      correct: 1,
      explanation: "O nó SA localiza-se na junção da VCS com o AD.",
    },
    {
      id: 14,
      question: "Qual estrutura anatômica impede o prolapso das válvulas das valvas atrioventriculares para dentro dos átrios durante a sístole ventricular?",
      options: [
        "Músculos pectíneos.",
        "Trabéculas cárneas.",
        "Cordas tendíneas e músculos papilares.",
        "Crista supraventricular.",
      ],
      correct: 2,
      explanation: "As cordas tendíneas e músculos papilares impedem o prolapso das válvulas AV.",
    },
    {
      id: 15,
      question: "No arco aórtico, o primeiro grande tronco arterial a emergir (da direita para a esquerda) é o:",
      options: [
        "Tronco braquiocefálico.",
        "Artéria carótida comum esquerda.",
        "Artéria subclávia esquerda.",
        "Tronco pulmonar.",
      ],
      correct: 0,
      explanation: "O tronco braquiocefálico é o primeiro ramo do arco aórtico.",
    },
    {
      id: 16,
      question: "A 'Base do Coração' é a sua face posterior, situada oposta ao ápice. Anatomicalmente, ela é formada predominantemente pelo:",
      options: [
        "Átrio direito.",
        "Átrio esquerdo.",
        "Ventrículo direito.",
        "Ventrículo esquerdo.",
      ],
      correct: 1,
      explanation: "A base do coração é formada predominantemente pelo átrio esquerdo.",
    },
    {
      id: 17,
      question: "Um trombo que se forma no átrio esquerdo e passa para o ventrículo esquerdo deve atravessar a valva:",
      options: [
        "Tricúspide.",
        "Semilunar pulmonar.",
        "Mitral (bicúspide).",
        "Semilunar aórtica.",
      ],
      correct: 2,
      explanation: "A valva mitral separa o AE do VE.",
    },
    {
      id: 18,
      question: "Sobre o ventrículo esquerdo, assinale a alternativa INCORRETA:",
      options: [
        "Possui paredes 2 a 3 vezes mais espessas que o ventrículo direito.",
        "Forma o ápice do coração.",
        "Sua via de saída é o cone arterial.",
        "Contém músculos papilares anterior e posterior.",
      ],
      correct: 2,
      explanation: "O cone arterial é a via de saída do ventrículo direito, não do esquerdo.",
    },
    {
      id: 19,
      question: "A veia cardíaca que acompanha a artéria interventricular anterior no sulco de mesmo nome é a:",
      options: [
        "Veia cardíaca média.",
        "Veia cardíaca parva.",
        "Veia cardíaca magna.",
        "Veia oblíqua do átrio esquerdo.",
      ],
      correct: 2,
      explanation: "A veia cardíaca magna acompanha a artéria interventricular anterior.",
    },
    {
      id: 20,
      question: "O local de ausculta da valva pulmonar situa-se no:",
      options: [
        "2º espaço intercostal esquerdo, junto à margem esternal.",
        "2º espaço intercostal direito, junto à margem esternal.",
        "5º espaço intercostal esquerdo, na linha hemiclavicular.",
        "5º espaço intercostal esquerdo, junto ao esterno.",
      ],
      correct: 1,
      explanation: "A valva pulmonar é ausculta no 2º EIC direito.",
    },
    {
      id: 21,
      question: "Qual componente do complexo estimulante do coração representa a única ponte elétrica entre o miocárdio atrial e ventricular?",
      options: [
        "Nó sinoatrial.",
        "Fascículo atrioventricular (Feixe de His).",
        "Fibras de Purkinje.",
        "Músculos pectíneos.",
      ],
      correct: 1,
      explanation: "O Feixe de His é a única ponte elétrica entre os átrios e ventrículos.",
    },
    {
      id: 22,
      question: "O tamponamento cardíaco ocorre quando o espaço entre o coração e o pericárdio é preenchido por líquido. Esse espaço é chamado de:",
      options: [
        "Espaço endocárdico.",
        "Cavidade pericárdica.",
        "Seio transverso.",
        "Átrio direito.",
      ],
      correct: 1,
      explanation: "O espaço entre o coração e o pericárdio é a cavidade pericárdica.",
    },
    {
      id: 23,
      question: "As veias pulmonares (em número de quatro) transportam sangue oxigenado e desembocam no:",
      options: [
        "Átrio direito.",
        "Átrio esquerdo.",
        "Ventrículo esquerdo.",
        "Pulmão.",
      ],
      correct: 1,
      explanation: "As veias pulmonares desembocam no átrio esquerdo.",
    },
    {
      id: 24,
      question: "A face diafragmática (inferior) do coração repousa sobre o diafragma e é formada principalmente pelo:",
      options: [
        "Ventrículo esquerdo e parte do ventrículo direito.",
        "Átrio direito.",
        "Átrio esquerdo e grandes vasos.",
        "Ventrículo direito exclusivamente.",
      ],
      correct: 0,
      explanation: "A face diafragmática é formada principalmente pelo VE e parte do VD.",
    },
    {
      id: 25,
      question: "A artéria coronária esquerda divide-se em dois ramos principais logo após sua origem. São eles:",
      options: [
        "Ramo marginal direito e ramo interventricular posterior.",
        "Ramo interventricular anterior e ramo circunflexo.",
        "Artéria do nó sinoatrial e ramo marginal esquerdo.",
        "Artéria carótida e artéria subclávia.",
      ],
      correct: 1,
      explanation: "A artéria coronária esquerda divide-se em ramo interventricular anterior e circunflexo.",
    },
    {
      id: 26,
      question: "Qual estrutura é o remanescente da circulação fetal que comunicava o tronco pulmonar com o arco da aorta?",
      options: [
        "Fossa oval.",
        "Ligamento arterial (Ducto arterial).",
        "Óstio do seio coronário.",
        "Crista terminal.",
      ],
      correct: 1,
      explanation: "O ligamento arterial é o remanescente do ducto arterial fetal.",
    },
    {
      id: 27,
      question: "Sobre a margem direita do coração, é correto afirmar que ela é:",
      options: [
        "Formada pelo ventrículo esquerdo.",
        "Reta e vertical, formada pelo átrio direito.",
        "Convexa e formada pelo átrio direito entre a VCS e VCI.",
        "Oblíqua e formada pelo ventrículo direito.",
      ],
      correct: 2,
      explanation: "A margem direita é convexa e formada pelo AD entre a VCS e VCI.",
    },
    {
      id: 28,
      question: "O sangue que sai do ventrículo direito em direção aos pulmões passa pela valva:",
      options: [
        "Mitral.",
        "Tricúspide.",
        "Pulmonar (semilunar).",
        "Aórtica.",
      ],
      correct: 2,
      explanation: "O sangue do VD passa pela valva pulmonar para chegar aos pulmões.",
    },
    {
      id: 29,
      question: "Na anatomia interna do átrio direito, a depressão semilunar no septo interatrial é a:",
      options: [
        "Crista terminal.",
        "Fossa oval.",
        "Óstio da veia cava superior.",
        "Aurícula direita.",
      ],
      correct: 1,
      explanation: "A fossa oval é a depressão semilunar no septo interatrial.",
    },
    {
      id: 30,
      question: "O 'Vestíbulo da Aorta' é uma região de parede lisa que leva à valva da aorta e localiza-se no:",
      options: [
        "Átrio esquerdo.",
        "Ventrículo direito.",
        "Ventrículo esquerdo.",
        "Tronco pulmonar.",
      ],
      correct: 2,
      explanation: "O vestíbulo da aorta localiza-se no VE.",
    },
    {
      id: 31,
      question: "A artéria que irriga o nó atrioventricular (AV) geralmente surge próximo à Crux Cordis e é ramo da:",
      options: [
        "Artéria coronária esquerda.",
        "Artéria coronária direita (na maioria dos casos).",
        "Artéria marginal anterior.",
        "Artéria carótida interna.",
      ],
      correct: 1,
      explanation: "A artéria do nó AV geralmente é ramo da coronária direita.",
    },
    {
      id: 32,
      question: "As fibras de Purkinje (ramos subendocárdicos) distribuem o impulso elétrico para:",
      options: [
        "Os átrios.",
        "O nó sinoatrial.",
        "As paredes dos ventrículos e músculos papilares.",
        "O esôfago.",
      ],
      correct: 2,
      explanation: "As fibras de Purkinje distribuem o impulso para os ventrículos e músculos papilares.",
    },
    {
      id: 33,
      question: "As valvas semilunares (aórtica e pulmonar) diferem das atrioventriculares por:",
      options: [
        "Possuírem cordas tendíneas mais resistentes.",
        "Não possuírem cordas tendíneas para sustentação.",
        "Serem formadas por apenas duas válvulas.",
        "Estarem localizadas na base dos átrios.",
      ],
      correct: 1,
      explanation: "As valvas semilunares não possuem cordas tendíneas.",
    },
    {
      id: 34,
      question: "O tronco braquiocefálico venoso esquerdo é formado pela junção da:",
      options: [
        "Veia jugular interna esquerda e veia subclávia esquerda.",
        "Veia cava superior e veia cava inferior.",
        "Veia cardíaca magna e parva.",
        "Veia ázigos e veia hemiázigos.",
      ],
      correct: 0,
      explanation: "O tronco braquiocefálico venoso esquerdo é formado pela VJI e VSC esquerdas.",
    },
    {
      id: 35,
      question: "Na grande circulação (sistêmica), o sangue sai do ventrículo esquerdo e retorna ao:",
      options: [
        "Átrio esquerdo através das veias pulmonares.",
        "Átrio direito através das veias cavas.",
        "Pulmão para oxigenação.",
        "Ventrículo direito.",
      ],
      correct: 1,
      explanation: "O sangue da grande circulação retorna ao AD pelas veias cavas.",
    },
    {
      id: 36,
      question: "Qual câmara cardíaca apresenta a 'aurícula' (orelha), uma bolsa muscular cônica que aumenta sua capacidade?",
      options: [
        "Apenas os ventrículos.",
        "Ambos os átrios (direito e esquerdo).",
        "Apenas o átrio direito.",
        "Apenas o ventrículo esquerdo.",
      ],
      correct: 1,
      explanation: "Ambos os átrios possuem aurículas.",
    },
    {
      id: 37,
      question: "Os músculos papilares septais do ventrículo direito fixam cordas tendíneas nas válvulas:",
      options: [
        "Anterior e posterior da valva mitral.",
        "Anterior e septal da valva tricúspide.",
        "Semilunares da aorta.",
        "Pectíneas do átrio.",
      ],
      correct: 1,
      explanation: "Os músculos papilares do VD fixam cordas na valva tricúspide.",
    },
    {
      id: 38,
      question: "O 'Cone Arterial' (infundíbulo) é a via de saída do:",
      options: [
        "Átrio direito.",
        "Ventrículo direito para o tronco pulmonar.",
        "Ventrículo esquerdo para a aorta.",
        "Átrio esquerdo.",
      ],
      correct: 1,
      explanation: "O cone arterial é a via de saída do VD para o tronco pulmonar.",
    },
    {
      id: 39,
      question: "A veia cardíaca parva drena as áreas supridas pela artéria coronária direita e drena para o:",
      options: [
        "Átrio esquerdo.",
        "Veia cava superior.",
        "Seio coronário (extremidade direita).",
        "Veia jugular.",
      ],
      correct: 2,
      explanation: "A veia cardíaca parva drena para o seio coronário.",
    },
    {
      id: 40,
      question: "Assinale a alternativa que apresenta a sequência CORRETA do fluxo sanguíneo no coração:",
      options: [
        "AD -> Mitral -> VD -> Tronco Pulmonar.",
        "AE -> Tricúspide -> VE -> Aorta.",
        "AD -> Tricúspide -> VD -> Tronco Pulmonar -> Pulmão -> Veias Pulmonares -> AE -> Mitral -> VE -> Aorta.",
        "VCI -> AE -> Mitral -> VE -> Tronco Pulmonar.",
      ],
      correct: 2,
      explanation: "A sequência correta do fluxo sanguíneo está na alternativa C.",
    },
  ],
  vascularizacao: [
    {
      id: 1,
      question: "Qual é o primeiro ramo da artéria carótida externa?",
      options: [
        "Artéria lingual",
        "Artéria tireóidea superior",
        "Artéria facial",
        "Artéria temporal superficial",
      ],
      correct: 1,
      explanation: "A artéria tireóidea superior é o primeiro ramo da carótida externa.",
    },
    {
      id: 2,
      question: "A artéria lingual é um ramo importante da carótida externa. Qual estrutura ela irriga principalmente?",
      options: [
        "A glândula parótida",
        "A língua e estruturas do assoalho oral",
        "O palato mole",
        "A faringe",
      ],
      correct: 1,
      explanation: "A artéria lingual irriga a língua e estruturas do assoalho oral.",
    },
    {
      id: 3,
      question: "Qual artéria é responsável pela irrigação do assoalho da boca e é ramo da artéria facial?",
      options: [
        "Artéria submental",
        "Artéria lingual profunda",
        "Artéria palatina maior",
        "Artéria alveolar superior",
      ],
      correct: 0,
      explanation: "A artéria submental é um ramo importante da artéria facial para o assoalho da boca.",
    },
    {
      id: 4,
      question: "A artéria facial irriga diversas estruturas faciais. Qual é o seu ramo terminal que irriga a região lacrimal?",
      options: [
        "Artéria labial superior",
        "Artéria labial inferior",
        "Artéria angular",
        "Artéria transversa da face",
      ],
      correct: 2,
      explanation: "A artéria angular é o terminal da facial, irrigando a região lacrimal.",
    },
    {
      id: 5,
      question: "Quais são os principais ramos da artéria facial que irrigam os lábios?",
      options: [
        "Artérias labiais e submental",
        "Artérias angulares e temporais",
        "Artérias mentonianas e alveolares",
        "Artérias infraorbitais e esfenopalatinas",
      ],
      correct: 0,
      explanation: "As artérias labiais e a submental são ramos diretos da artéria facial na face.",
    },
    {
      id: 6,
      question: "A artéria maxilar é o ramo terminal de maior calibre da carótida externa. Um de seus ramos, a artéria infraorbital, irriga:",
      options: [
        "Passa pelo sulco infraorbital e irriga o seio maxilar, arcada dentária e pálpebra inferior.",
        "Atravessa o forame espinhoso para irrigar as meninges cranianas.",
        "Irriga exclusivamente o músculo masseter para a mastigação.",
        "Distribui-se pela mucosa nasal e nasofaringe.",
      ],
      correct: 0,
      explanation: "A infraorbital passa pelo canal homônimo e supre o seio maxilar e dentes.",
    },
    {
      id: 7,
      question: "Paciente com sangramento arterial profuso na nasofaringe após procedimento cirúrgico. O vaso provavelmente envolvido é a artéria esfenopalatina. Esse vaso é uma continuação ou ramo de qual estrutura?",
      options: [
        "Artéria Facial.",
        "Artéria Temporal Superficial.",
        "Artéria Maxilar.",
        "Artéria Lingual.",
      ],
      correct: 2,
      explanation: "A artéria esfenopalatina é um dos ramos terminais da artéria maxilar.",
    },
    {
      id: 8,
      question: "Sobre a artéria temporal superficial (menor ramo terminal da carótida externa), assinale a alternativa que descreve corretamente suas subdivisões terminais no couro cabeludo:",
      options: [
        "Ramos frontal e parietal, que irrigam o escalpo.",
        "Ramo submental e ramo angular.",
        "Ramos massetérico e esfenopalatino.",
        "Ramos parotídeos e auriculares anteriores.",
      ],
      correct: 0,
      explanation: "A temporal superficial termina dividindo-se em ramos frontal e parietal.",
    },
    {
      id: 9,
      question: "Um paciente apresenta um tumor na glândula parótida. O cirurgião deve ter cautela com a artéria facial transversa. Qual a origem e trajeto desse vaso?",
      options: [
        "Origina-se da artéria facial e segue profundamente ao músculo masseter.",
        "Origina-se da artéria temporal superficial e cruza a face superficialmente ao masseter.",
        "É o primeiro ramo da carótida externa e corre medialmente ao músculo hioglosso.",
        "Emerge do tronco braquiocefálico e irriga a pele do pescoço.",
      ],
      correct: 1,
      explanation: "A facial transversa nasce da temporal superficial dentro da parótida e cruza o masseter.",
    },
    {
      id: 10,
      question: "Considerando os ramos posteriores da carótida externa, qual artéria é responsável pela irrigação da musculatura retroauricular, orelha e couro cabeludo posterior?",
      options: [
        "Artéria Occipital.",
        "Artéria Auricular Posterior.",
        "Artéria Faríngea Ascendente.",
        "Artéria Temporal Medial.",
      ],
      correct: 1,
      explanation: "A artéria auricular posterior segue entre o processo mastoide e a orelha.",
    },
    {
      id: 11,
      question: "Qual é a origem da artéria oftálmica?",
      options: [
        "Carótida externa",
        "Carótida interna",
        "Artéria maxilar",
        "Artéria temporal",
      ],
      correct: 1,
      explanation: "A artéria oftálmica origina-se da carótida interna.",
    },
    {
      id: 12,
      question: "Qual estrutura passa pelo forame jugular?",
      options: [
        "Artéria carótida interna",
        "Veias jugulares internas",
        "Nervo vago",
        "Todas as alternativas anteriores",
      ],
      correct: 3,
      explanation: "O forame jugular permite a passagem de estruturas vasculares e nervosas.",
    },
    {
      id: 13,
      question: "Qual artéria é a continuação da carótida interna após penetrar o crânio?",
      options: [
        "Artéria cerebral anterior",
        "Artéria cerebral média",
        "Artéria cerebral posterior",
        "Artéria comunicante anterior",
      ],
      correct: 1,
      explanation: "A carótida interna continua como artéria cerebral média.",
    },
    {
      id: 14,
      question: "Qual é o principal tributário da veia jugular interna?",
      options: [
        "Veia facial",
        "Veia lingual",
        "Veia temporal superficial",
        "Todas as alternativas anteriores",
      ],
      correct: 3,
      explanation: "A veia jugular interna recebe múltiplos tributários.",
    },
    {
      id: 15,
      question: "Qual artéria irriga a mandíbula?",
      options: [
        "Artéria alveolar inferior",
        "Artéria alveolar superior",
        "Artéria facial",
        "Artéria lingual",
      ],
      correct: 0,
      explanation: "A artéria alveolar inferior irriga a mandíbula e os dentes inferiores.",
    },
    {
      id: 16,
      question: "Qual ramo da carótida externa irriga a glândula parótida?",
      options: [
        "Artéria temporal superficial",
        "Artéria maxilar",
        "Artéria lingual",
        "Artéria facial",
      ],
      correct: 0,
      explanation: "A artéria temporal superficial passa através da glândula parótida.",
    },
    {
      id: 17,
      question: "A veia jugular interna é a principal veia de drenagem do viscerocrânio. Qual é a sua origem?",
      options: [
        "Forame jugular",
        "Bulbo da veia jugular interna",
        "Confluência das veias cerebrais",
        "Seio cavernoso",
      ],
      correct: 2,
      explanation: "A veia jugular interna origina-se da confluência das veias cerebrais.",
    },
    {
      id: 18,
      question: "Qual estrutura marca o limite anterior da cavidade oral?",
      options: [
        "Palato duro",
        "Lábios",
        "Dentes",
        "Língua",
      ],
      correct: 1,
      explanation: "Os lábios marcam o limite anterior da cavidade oral.",
    },
    {
      id: 19,
      question: "Qual é a função do palato mole?",
      options: [
        "Mastigação",
        "Deglutição e fala",
        "Apenas sensibilidade",
        "Apenas proteção",
      ],
      correct: 1,
      explanation: "O palato mole é importante para a deglutição e fala.",
    },
    {
      id: 20,
      question: "Qual músculo é responsável pela elevação da mandíbula?",
      options: [
        "Músculo masseter",
        "Músculo temporal",
        "Músculo pterigóideo medial",
        "Todas as alternativas anteriores",
      ],
      correct: 3,
      explanation: "Os músculos masseter, temporal e pterigóideo medial elevam a mandíbula.",
    },
    {
      id: 21,
      question: "Qual é o número total de dentes em um adulto?",
      options: [
        "20 dentes",
        "28 dentes",
        "32 dentes",
        "36 dentes",
      ],
      correct: 2,
      explanation: "Um adulto possui 32 dentes permanentes.",
    },
    {
      id: 22,
      question: "Qual estrutura forma o teto da cavidade oral?",
      options: [
        "Palato duro",
        "Palato mole",
        "Ambos",
        "Nenhum dos anteriores",
      ],
      correct: 2,
      explanation: "O teto é formado pelo palato duro (anterior) e palato mole (posterior).",
    },
    {
      id: 23,
      question: "Qual é a origem do nervo trigêmeo (CN V)?",
      options: [
        "Tronco encefálico",
        "Medula espinal",
        "Bulbo raquidiano",
        "Ponte",
      ],
      correct: 0,
      explanation: "O nervo trigêmeo origina-se do tronco encefálico.",
    },
    {
      id: 24,
      question: "Qual glândula salivar está localizada sob a língua?",
      options: [
        "Glândula parótida",
        "Glândula submandibular",
        "Glândula sublingual",
        "Glândulas menores",
      ],
      correct: 2,
      explanation: "A glândula sublingual está localizada sob a língua.",
    },
    {
      id: 25,
      question: "Qual é a função da língua na cavidade oral?",
      options: [
        "Apenas paladar",
        "Apenas mastigação",
        "Mastigação, deglutição, fala e paladar",
        "Apenas proteção",
      ],
      correct: 2,
      explanation: "A língua tem múltiplas funções.",
    },
    {
      id: 26,
      question: "Qual estrutura separa a cavidade oral da cavidade nasal?",
      options: [
        "Palato duro",
        "Palato mole",
        "Septo nasal",
        "Vômer",
      ],
      correct: 0,
      explanation: "O palato duro separa a cavidade oral da cavidade nasal.",
    },
    {
      id: 27,
      question: "Qual é a principal artéria que irriga o coração?",
      options: [
        "Artéria carótida interna",
        "Artéria coronária",
        "Artéria aorta",
        "Artéria subclávia",
      ],
      correct: 1,
      explanation: "A artéria coronária é a principal responsável pela irrigação do coração.",
    },
    {
      id: 28,
      question: "Qual vaso sanguíneo é responsável pelo transporte de sangue oxigenado do coração para o corpo?",
      options: [
        "Veia cava superior",
        "Artéria aorta",
        "Tronco pulmonar",
        "Veia pulmonar",
      ],
      correct: 1,
      explanation: "A artéria aorta transporta sangue oxigenado do coração para o corpo.",
    },
    {
      id: 29,
      question: "Qual é a função das veias do viscerocrânio?",
      options: [
        "Transportar sangue arterial",
        "Drenar sangue venoso das estruturas do viscerocrânio",
        "Irrigar os músculos masticadores",
        "Apenas nutrição das glândulas salivares",
      ],
      correct: 1,
      explanation: "As veias drenam sangue venoso das estruturas do viscerocrânio.",
    },
    {
      id: 30,
      question: "Qual é a principal diferença entre a carótida interna e a carótida externa?",
      options: [
        "A carótida interna irriga estruturas externas da cabeça",
        "A carótida externa irriga o encéfalo e estruturas intracranianas",
        "A carótida interna irriga o encéfalo e estruturas intracranianas",
        "Não há diferença funcional entre elas",
      ],
      correct: 2,
      explanation: "A carótida interna irriga o encéfalo e estruturas intracranianas.",
    },
  ],
  "cavidade-oral": [
    {
      id: 1,
      question: "Durante um exame físico de rotina, um médico observa a saída de saliva na região do vestíbulo da boca, oposta ao segundo molar superior. Qual estrutura está sendo avaliada?",
      options: [
        "Óstio do ducto sublingual.",
        "Óstio do ducto submandibular.",
        "Óstio do ducto parotídeo.",
        "Carúncula sublingual.",
      ],
      correct: 2,
      explanation: "O óstio do ducto parotídeo abre-se no vestíbulo oposto ao segundo molar superior.",
    },
    {
      id: 2,
      question: "Um paciente de 25 anos sofre uma laceração profunda na bochecha. O cirurgião precisa identificar o principal músculo que forma a parede móvel dessa região. Assinale a alternativa CORRETA:",
      options: [
        "Músculo masseter.",
        "Músculo bucinador.",
        "Músculo orbicular da boca.",
        "Músculo milo-hioideo.",
      ],
      correct: 1,
      explanation: "O músculo bucinador forma a parede móvel da bochecha.",
    },
    {
      id: 3,
      question: "Uma criança de 5 anos apresenta 'língua presa', o que dificulta a fala. O médico diagnostica anquiloglossia. Qual estrutura anatômica está excessivamente curta ou fixada anteriormente nesse caso?",
      options: [
        "Prega sublingual.",
        "Frênulo labial inferior.",
        "Sulco terminal da língua.",
        "Frênulo da língua.",
      ],
      correct: 3,
      explanation: "O frênulo da língua está excessivamente curto na anquiloglossia.",
    },
    {
      id: 4,
      question: "Durante uma cirurgia de remoção de um tumor no palato duro, ocorre um sangramento arterial intenso. Qual artéria é a principal responsável pela irrigação do palato duro?",
      options: [
        "Artéria palatina menor.",
        "Artéria palatina maior.",
        "Artéria palatina ascendente.",
        "Artéria lingual profunda.",
      ],
      correct: 1,
      explanation: "A artéria palatina maior é a principal responsável pela irrigação do palato duro.",
    },
    {
      id: 5,
      question: "Um paciente apresenta perda da sensibilidade especial (paladar) nos 2/3 anteriores da língua, mas a sensibilidade geral está preservada. Qual nervo foi especificamente lesionado?",
      options: [
        "Nervo lingual (ramo do V3).",
        "Nervo corda do tímpano (ramo do VII).",
        "Nervo glossofaríngeo (IX).",
        "Nervo hipoglosso (XII).",
      ],
      correct: 1,
      explanation: "O nervo corda do tímpano fornece paladar aos 2/3 anteriores da língua.",
    },
    {
      id: 6,
      question: "Assinale a alternativa INCORRETA sobre os limites da cavidade oral:",
      options: [
        "O limite anterior é formado pelos lábios.",
        "O assoalho é constituído pelos músculos milo-hioideo e gênio-hioideo.",
        "O limite posterior é o istmo das fauces.",
        "O teto é formado exclusivamente pelo palato mole.",
      ],
      correct: 3,
      explanation: "O teto é formado pelo palato duro e palato mole.",
    },
    {
      id: 7,
      question: "Um paciente apresenta disfagia. O médico observa que o palato mole não se eleva adequadamente. Qual músculo é responsável por tensionar o palato mole?",
      options: [
        "Músculo levantador do véu palatino.",
        "Músculo da úvula.",
        "Músculo tensor do véu palatino.",
        "Músculo palatoglosso.",
      ],
      correct: 2,
      explanation: "O músculo tensor do véu palatino tensiona o palato mole.",
    },
    {
      id: 8,
      question: "Durante a inspeção do dorso da língua, um estudante identifica papilas organizadas em formato de 'V'. Estas estruturas são as:",
      options: [
        "Papilas filiformes.",
        "Papilas fungiformes.",
        "Papilas folhadas.",
        "Papilas circunvaladas.",
      ],
      correct: 3,
      explanation: "As papilas circunvaladas estão organizadas em formato de V.",
    },
    {
      id: 9,
      question: "Um paciente com sialolitiase apresenta dor no assoalho da boca. Onde o ducto submandibular se abre?",
      options: [
        "Na papila do ducto parotídeo.",
        "No forame cego da língua.",
        "Na carúncula sublingual, ao lado do frênulo da língua.",
        "Ao longo das pregas palatinas transversas.",
      ],
      correct: 2,
      explanation: "O ducto submandibular abre-se na carúncula sublingual.",
    },
    {
      id: 10,
      question: "Qual músculo extrínseco da língua é o principal responsável por protrair a língua?",
      options: [
        "Músculo estiloglosso.",
        "Músculo genioglosso.",
        "Músculo hioglosso.",
        "Músculo palatoglosso.",
      ],
      correct: 1,
      explanation: "O músculo genioglosso protrai a língua.",
    },
    {
      id: 11,
      question: "Em uma emergência, um paciente apresenta sangramento na base da língua. Qual nervo é responsável pela sensibilidade nesta região?",
      options: [
        "Nervo lingual.",
        "Nervo glossofaríngeo (IX).",
        "Nervo vago (X).",
        "Nervo facial (VII).",
      ],
      correct: 1,
      explanation: "O nervo glossofaríngeo fornece sensibilidade ao 1/3 posterior da língua.",
    },
    {
      id: 12,
      question: "Assinale a alternativa CORRETA sobre as glândulas salivares:",
      options: [
        "A glândula parótida é a menor das glândulas maiores.",
        "A glândula sublingual situa-se entre a mandíbula e o músculo genioglosso.",
        "A glândula submandibular secreta saliva exclusivamente mucosa.",
        "O ducto parotídeo atravessa o músculo masseter.",
      ],
      correct: 3,
      explanation: "O ducto parotídeo atravessa o músculo masseter.",
    },
    {
      id: 13,
      question: "Um paciente não consegue 'enrolar' a língua, mas consegue movê-la para fora. Quais músculos estão comprometidos?",
      options: [
        "Músculos extrínsecos da língua.",
        "Músculo orbicular da boca.",
        "Músculos intrínsecos da língua.",
        "Músculos do diafragma oral.",
      ],
      correct: 2,
      explanation: "Os músculos intrínsecos alteram o formato da língua.",
    },
    {
      id: 14,
      question: "Sobre a irrigação e drenagem da língua, é correto afirmar que:",
      options: [
        "A irrigação provém de ramos da artéria carótida interna.",
        "A drenagem venosa é feita por tributárias da veia jugular interna.",
        "A artéria sublingual é um ramo da artéria maxilar.",
        "A artéria profunda da língua supre apenas a raiz.",
      ],
      correct: 1,
      explanation: "A drenagem venosa é feita por tributárias da veia jugular interna.",
    },
    {
      id: 15,
      question: "Um paciente apresenta inflamação na gengiva inserida. Qual é a característica dessa região?",
      options: [
        "Vermelho-brilhante e não queratinizado.",
        "Róseo, pontilhado e queratinizado.",
        "Móvel e não aderido.",
        "Localizada acima da linha de oclusão.",
      ],
      correct: 1,
      explanation: "A gengiva inserida é rósea, pontilhada e queratinizada.",
    },
    {
      id: 16,
      question: "Qual estrutura é considerada o remanescente do ducto tireoglosso embrionário?",
      options: [
        "Sulco mediano.",
        "Forame cego.",
        "Úvula.",
        "Sulco terminal.",
      ],
      correct: 1,
      explanation: "O forame cego é o remanescente do ducto tireoglosso.",
    },
    {
      id: 17,
      question: "Assinale a alternativa INCORRETA sobre os músculos do palato mole:",
      options: [
        "O músculo palatofaringeu traciona as paredes da faringe.",
        "O músculo da úvula encurta a úvula.",
        "O músculo palatoglosso eleva a parte posterior da língua.",
        "Todos são inervados pelo nervo trigêmeo.",
      ],
      correct: 3,
      explanation: "Os músculos do palato mole são inervados pelo nervo vago, não trigêmeo.",
    },
    {
      id: 18,
      question: "Um paciente apresenta um abscesso no espaço retromolar. Este espaço comunica:",
      options: [
        "O vestíbulo com a cavidade oral própria.",
        "A cavidade oral com a nasofaringe.",
        "O palato duro com o palato mole.",
        "A região parotídea com a fossa infratemporal.",
      ],
      correct: 0,
      explanation: "O espaço retromolar comunica o vestíbulo com a cavidade oral.",
    },
    {
      id: 19,
      question: "Durante um procedimento odontológico, qual nervo deve ser anestesiado para insensibilizar a mucosa anterior do palato duro?",
      options: [
        "Nervo palatino maior.",
        "Nervo nasopalatino.",
        "Nervo palatino menor.",
        "Nervo alveolar superior.",
      ],
      correct: 1,
      explanation: "O nervo nasopalatino supre a mucosa anterior do palato duro.",
    },
    {
      id: 20,
      question: "Qual músculo forma o 'diafragma oral' ou assoalho da boca?",
      options: [
        "Músculo genioglosso.",
        "Músculo milo-hioideo.",
        "Músculo estilohioideo.",
        "Músculo digástrico.",
      ],
      correct: 1,
      explanation: "O músculo milo-hioideo forma o assoalho da boca.",
    },
    {
      id: 21,
      question: "Qual é a função das rugas palatinas?",
      options: [
        "Proteção contra refluxo alimentar.",
        "Auxílio na manipulação do alimento.",
        "Secretar saliva serosa.",
        "Fixação do músculo tensor do véu.",
      ],
      correct: 1,
      explanation: "As rugas palatinas auxiliam na manipulação do alimento.",
    },
    {
      id: 22,
      question: "Um paciente com lesão do nervo hipoglosso apresentaria qual sinal clínico?",
      options: [
        "Perda de paladar no ápice.",
        "Perda de sensibilidade tátil.",
        "Desvio da língua para o lado lesionado.",
        "Incapacidade de sentir amargo.",
      ],
      correct: 2,
      explanation: "Lesão do nervo hipoglosso causa desvio da língua para o lado lesionado.",
    },
    {
      id: 23,
      question: "Qual é a principal glândula salivar em relação ao volume de saliva produzida?",
      options: [
        "Glândula parótida.",
        "Glândula submandibular.",
        "Glândula sublingual.",
        "Glândulas menores.",
      ],
      correct: 0,
      explanation: "A glândula parótida produz a maior quantidade de saliva.",
    },
    {
      id: 24,
      question: "Qual estrutura marca o limite posterior da cavidade oral?",
      options: [
        "Palato mole.",
        "Istmo das fauces.",
        "Úvula.",
        "Faringe.",
      ],
      correct: 1,
      explanation: "O istmo das fauces marca o limite posterior da cavidade oral.",
    },
    {
      id: 25,
      question: "Qual é a inervação sensorial dos 2/3 anteriores da língua?",
      options: [
        "Nervo glossofaríngeo.",
        "Nervo lingual.",
        "Nervo vago.",
        "Nervo hipoglosso.",
      ],
      correct: 1,
      explanation: "O nervo lingual fornece sensibilidade geral aos 2/3 anteriores.",
    },
    {
      id: 26,
      question: "Qual artéria é a continuação da artéria facial após passar pela mandíbula?",
      options: [
        "Artéria angular.",
        "Artéria labial superior.",
        "Artéria submental.",
        "Artéria infraorbital.",
      ],
      correct: 0,
      explanation: "A artéria angular é a continuação terminal da artéria facial.",
    },
    {
      id: 27,
      question: "Qual é a função principal do palato duro?",
      options: [
        "Deglutição.",
        "Fala.",
        "Separação entre cavidade oral e nasal.",
        "Mastigação.",
      ],
      correct: 2,
      explanation: "O palato duro separa a cavidade oral da cavidade nasal.",
    },
    {
      id: 28,
      question: "Qual estrutura anatômica é responsável pelo paladar nos 2/3 posteriores da língua?",
      options: [
        "Nervo lingual.",
        "Nervo corda do tímpano.",
        "Nervo glossofaríngeo.",
        "Nervo vago.",
      ],
      correct: 2,
      explanation: "O nervo glossofaríngeo fornece paladar ao 1/3 posterior.",
    },
    {
      id: 29,
      question: "Qual é a origem da artéria lingual?",
      options: [
        "Artéria carótida interna.",
        "Artéria carótida externa.",
        "Artéria facial.",
        "Artéria maxilar.",
      ],
      correct: 1,
      explanation: "A artéria lingual origina-se da carótida externa.",
    },
    {
      id: 30,
      question: "Qual músculo é responsável pela oclusão dos lábios?",
      options: [
        "Músculo bucinador.",
        "Músculo orbicular da boca.",
        "Músculo levantador do lábio superior.",
        "Músculo masseter.",
      ],
      correct: 1,
      explanation: "O músculo orbicular da boca é responsável pela oclusão dos lábios.",
    },
  ],
  orelha: [
    {
      id: 1,
      question: "Um paciente de 25 anos apresenta uma laceração no terço lateral do meato acústico externo. Qual a constituição anatômica predominante dessa região?",
      options: [
        "Óssea; artéria caroticotimpânica",
        "Cartilagínea; ramos da artéria carótida externa",
        "Fibrosa; artéria timpânica anterior",
        "Membranácea; artéria labiríntica",
      ],
      correct: 1,
      explanation: "O terço lateral do meato é cartilagíneo e nutrido por ramos da carótida externa.",
    },
    {
      id: 2,
      question: "Durante uma cirurgia de mastoidectomia, qual é a inervação do músculo estapédio?",
      options: [
        "Ramo mandibular do nervo trigêmeo (V3)",
        "Nervo facial (VII par)",
        "Nervo vago (X par)",
        "Nervo acessório (XI par)",
      ],
      correct: 1,
      explanation: "O músculo estapédio é suprido pelo nervo facial.",
    },
    {
      id: 3,
      question: "Em qual osso se localiza a cavidade timpânica?",
      options: [
        "Porção escamosa do osso temporal",
        "Porção petrosa do osso temporal",
        "Porção mastóidea do osso temporal",
        "Osso etmoide",
      ],
      correct: 1,
      explanation: "A orelha média fica na porção petrosa do osso temporal.",
    },
    {
      id: 4,
      question: "Qual é a função da tuba auditiva?",
      options: [
        "Transmitir sons para o labirinto",
        "Equilibrar a pressão entre a orelha média e a nasofaringe",
        "Produzir cerúmen",
        "Amplificar vibrações sonoras",
      ],
      correct: 1,
      explanation: "A tuba auditiva equilibra a pressão entre a orelha média e nasofaringe.",
    },
    {
      id: 5,
      question: "Qual é o primeiro ossículo da cadeia ossicular?",
      options: [
        "Bigorna",
        "Estribo",
        "Martelo",
        "Incus",
      ],
      correct: 2,
      explanation: "O martelo é o primeiro ossículo que recebe as vibrações do tímpano.",
    },
    {
      id: 6,
      question: "Qual nervo fornece inervação sensorial ao meato acústico externo?",
      options: [
        "Nervo trigêmeo (V)",
        "Nervo facial (VII)",
        "Nervo vago (X)",
        "Nervo glossofaríngeo (IX)",
      ],
      correct: 2,
      explanation: "O nervo vago fornece inervação sensorial ao meato acústico externo.",
    },
    {
      id: 7,
      question: "Qual é a função principal da membrana timpânica?",
      options: [
        "Proteger o labirinto",
        "Transmitir vibrações sonoras para os ossículos",
        "Produzir cerúmen",
        "Equilibrar pressão",
      ],
      correct: 1,
      explanation: "A membrana timpânica transmite vibrações sonoras para os ossículos.",
    },
    {
      id: 8,
      question: "Qual estrutura separa a orelha média da orelha interna?",
      options: [
        "Membrana timpânica",
        "Janela oval",
        "Janela redonda",
        "Tuba auditiva",
      ],
      correct: 1,
      explanation: "A janela oval separa a orelha média da orelha interna.",
    },
    {
      id: 9,
      question: "Qual é a função do labirinto membranoso?",
      options: [
        "Transmitir sons",
        "Equilíbrio e audição",
        "Produzir cerúmen",
        "Drenar fluidos",
      ],
      correct: 1,
      explanation: "O labirinto membranoso é responsável pelo equilíbrio e audição.",
    },
    {
      id: 10,
      question: "Qual nervo fornece inervação motora aos músculos da orelha?",
      options: [
        "Nervo trigêmeo",
        "Nervo facial",
        "Nervo vago",
        "Nervo acessório",
      ],
      correct: 1,
      explanation: "O nervo facial fornece inervação motora aos músculos da orelha.",
    },
    {
      id: 11,
      question: "Qual é a estrutura responsável pela amplificação do som na orelha média?",
      options: [
        "Membrana timpânica",
        "Cadeia ossicular",
        "Tuba auditiva",
        "Labirinto",
      ],
      correct: 1,
      explanation: "A cadeia ossicular amplifica as vibrações sonoras.",
    },
    {
      id: 12,
      question: "Qual é a origem embrionária da orelha externa?",
      options: [
        "Endoderme",
        "Mesoderme",
        "Ectoderme",
        "Mesoderme e endoderme",
      ],
      correct: 2,
      explanation: "A orelha externa origina-se da ectoderme.",
    },
    {
      id: 13,
      question: "Qual estrutura do labirinto é responsável pela detecção de movimentos lineares?",
      options: [
        "Canais semicirculares",
        "Cóclea",
        "Utrículo e sáculo",
        "Órgão de Corti",
      ],
      correct: 2,
      explanation: "O utrículo e sáculo detectam movimentos lineares.",
    },
    {
      id: 14,
      question: "Qual é a função do órgão de Corti?",
      options: [
        "Equilíbrio",
        "Audição",
        "Drenagem de fluidos",
        "Produção de cerúmen",
      ],
      correct: 1,
      explanation: "O órgão de Corti é responsável pela audição.",
    },
    {
      id: 15,
      question: "Qual estrutura contém os receptores sensoriais para audição?",
      options: [
        "Canais semicirculares",
        "Cóclea",
        "Utrículo",
        "Sáculo",
      ],
      correct: 1,
      explanation: "A cóclea contém os receptores sensoriais para audição.",
    },
    {
      id: 16,
      question: "Qual nervo é responsável pela transmissão de impulsos auditivos?",
      options: [
        "Nervo trigêmeo",
        "Nervo facial",
        "Nervo vestibulococlear",
        "Nervo vago",
      ],
      correct: 2,
      explanation: "O nervo vestibulococlear transmite impulsos auditivos.",
    },
    {
      id: 17,
      question: "Qual é a estrutura responsável pela produção de cerúmen?",
      options: [
        "Glândulas sebáceas",
        "Glândulas sudoríparas",
        "Glândulas ceruminosas",
        "Glândulas salivares",
      ],
      correct: 2,
      explanation: "As glândulas ceruminosas produzem cerúmen.",
    },
    {
      id: 18,
      question: "Qual é a função principal do cerúmen?",
      options: [
        "Amplificar sons",
        "Proteger e lubrificar o meato",
        "Transmitir vibrações",
        "Equilibrar pressão",
      ],
      correct: 1,
      explanation: "O cerúmen protege e lubrifica o meato acústico externo.",
    },
    {
      id: 19,
      question: "Qual estrutura separa a orelha interna da cavidade craniana?",
      options: [
        "Janela oval",
        "Janela redonda",
        "Osso temporal",
        "Membrana timpânica",
      ],
      correct: 2,
      explanation: "O osso temporal separa a orelha interna da cavidade craniana.",
    },
    {
      id: 20,
      question: "Qual é a função dos canais semicirculares?",
      options: [
        "Audição",
        "Detecção de movimentos rotatórios",
        "Produção de fluido",
        "Transmissão de sons",
      ],
      correct: 1,
      explanation: "Os canais semicirculares detectam movimentos rotatórios.",
    },
  ],
  olho: [
    {
      id: 1,
      question: "Qual é a camada mais externa do olho responsável pela proteção e manutenção da forma?",
      options: [
        "Retina",
        "Coroide",
        "Esclera",
        "Córnea",
      ],
      correct: 2,
      explanation: "A esclera é a camada mais externa, branca e opaca.",
    },
    {
      id: 2,
      question: "Qual estrutura do olho é responsável pela refração da luz?",
      options: [
        "Retina",
        "Cristalino",
        "Córnea",
        "Humor vítreo",
      ],
      correct: 2,
      explanation: "A córnea é a principal responsável pela refração inicial da luz.",
    },
    {
      id: 3,
      question: "Qual é a função da íris?",
      options: [
        "Refração de luz",
        "Regulação da quantidade de luz que entra no olho",
        "Acomodação visual",
        "Transmissão de impulsos visuais",
      ],
      correct: 1,
      explanation: "A íris regula a quantidade de luz através da pupila.",
    },
    {
      id: 4,
      question: "Qual estrutura do olho é responsável pela acomodação visual?",
      options: [
        "Retina",
        "Cristalino",
        "Córnea",
        "Esclera",
      ],
      correct: 1,
      explanation: "O cristalino muda de forma para acomodação visual.",
    },
    {
      id: 5,
      question: "Qual é a função do humor vítreo?",
      options: [
        "Refração de luz",
        "Manutenção da forma do olho e transmissão de luz",
        "Proteção da retina",
        "Regulação de pressão",
      ],
      correct: 1,
      explanation: "O humor vítreo mantém a forma do olho e transmite luz.",
    },
    {
      id: 6,
      question: "Qual camada do olho contém os fotorreceptores?",
      options: [
        "Esclera",
        "Coroide",
        "Retina",
        "Córnea",
      ],
      correct: 2,
      explanation: "A retina contém os fotorreceptores (bastonetes e cones).",
    },
    {
      id: 7,
      question: "Qual é a função da coroide?",
      options: [
        "Proteção mecânica",
        "Refração de luz",
        "Nutrição da retina e regulação de luz",
        "Transmissão de impulsos",
      ],
      correct: 2,
      explanation: "A coroide nutre a retina e regula a quantidade de luz.",
    },
    {
      id: 8,
      question: "Qual estrutura do olho forma a câmara anterior?",
      options: [
        "Cristalino e retina",
        "Córnea e íris",
        "Esclera e coroide",
        "Córnea e cristalino",
      ],
      correct: 3,
      explanation: "A câmara anterior é formada entre a córnea e o cristalino.",
    },
    {
      id: 9,
      question: "Qual é a função do humor aquoso?",
      options: [
        "Transmissão de luz",
        "Nutrição da córnea e cristalino, manutenção de pressão",
        "Proteção mecânica",
        "Acomodação visual",
      ],
      correct: 1,
      explanation: "O humor aquoso nutre estruturas e mantém a pressão intraocular.",
    },
    {
      id: 10,
      question: "Qual nervo é responsável pela transmissão de impulsos visuais?",
      options: [
        "Nervo óptico",
        "Nervo trigêmeo",
        "Nervo facial",
        "Nervo vago",
      ],
      correct: 0,
      explanation: "O nervo óptico transmite impulsos visuais ao cérebro.",
    },
    {
      id: 11,
      question: "Qual é a estrutura responsável pela visão de cores?",
      options: [
        "Bastonetes",
        "Cones",
        "Células ganglionares",
        "Células bipolares",
      ],
      correct: 1,
      explanation: "Os cones são responsáveis pela visão de cores.",
    },
    {
      id: 12,
      question: "Qual estrutura do olho é responsável pela visão em baixa luminosidade?",
      options: [
        "Cones",
        "Bastonetes",
        "Células ganglionares",
        "Células horizontais",
      ],
      correct: 1,
      explanation: "Os bastonetes são responsáveis pela visão em baixa luminosidade.",
    },
    {
      id: 13,
      question: "Qual é a função da mácula?",
      options: [
        "Proteção do olho",
        "Visão de cores e detalhes",
        "Regulação de pressão",
        "Transmissão de impulsos",
      ],
      correct: 1,
      explanation: "A mácula é responsável pela visão de cores e detalhes.",
    },
    {
      id: 14,
      question: "Qual estrutura do olho é responsável pelo ponto cego?",
      options: [
        "Mácula",
        "Disco óptico",
        "Fóvea",
        "Retina periférica",
      ],
      correct: 1,
      explanation: "O disco óptico é o ponto cego do olho.",
    },
    {
      id: 15,
      question: "Qual é a função das glândulas lacrimais?",
      options: [
        "Proteção mecânica",
        "Produção de lágrimas para lubrificação e proteção",
        "Refração de luz",
        "Regulação de pressão",
      ],
      correct: 1,
      explanation: "As glândulas lacrimais produzem lágrimas para lubrificação.",
    },
    {
      id: 16,
      question: "Qual estrutura drena as lágrimas?",
      options: [
        "Glândulas lacrimais",
        "Pálpebras",
        "Sistema de drenagem lacrimal",
        "Conjuntiva",
      ],
      correct: 2,
      explanation: "O sistema de drenagem lacrimal drena as lágrimas.",
    },
    {
      id: 17,
      question: "Qual é a função da conjuntiva?",
      options: [
        "Refração de luz",
        "Proteção e lubrificação da córnea",
        "Transmissão de impulsos",
        "Regulação de pressão",
      ],
      correct: 1,
      explanation: "A conjuntiva protege e lubrifica a córnea.",
    },
    {
      id: 18,
      question: "Qual estrutura do olho forma o ângulo iridocorneal?",
      options: [
        "Córnea e esclera",
        "Íris e córnea",
        "Íris e esclera",
        "Cristalino e íris",
      ],
      correct: 1,
      explanation: "O ângulo iridocorneal é formado entre a íris e a córnea.",
    },
    {
      id: 19,
      question: "Qual é a função do músculo ciliar?",
      options: [
        "Regulação da pupila",
        "Acomodação visual e regulação do humor aquoso",
        "Proteção do olho",
        "Transmissão de impulsos",
      ],
      correct: 1,
      explanation: "O músculo ciliar realiza acomodação e regula o humor aquoso.",
    },
    {
      id: 20,
      question: "Qual nervo fornece inervação sensorial à córnea?",
      options: [
        "Nervo facial",
        "Nervo trigêmeo",
        "Nervo vago",
        "Nervo óptico",
      ],
      correct: 1,
      explanation: "O nervo trigêmeo fornece inervação sensorial à córnea.",
    },
  ],
};
